// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagementWeb.Infrastructure.Persistence;

#nullable disable

namespace ProjectManagementWeb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830185719_AddProjectVersionNumber")]
    partial class AddProjectVersionNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AccountTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.BusinessCodeCounter", b =>
                {
                    b.Property<string>("CodeType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.HasKey("CodeType", "BusinessDate");

                    b.ToTable("BusinessCodeCounters", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessCodeCounters_CodeType", "[CodeType] IN ('Project', 'Task')");

                            t.HasCheckConstraint("CK_BusinessCodeCounters_LastValue", "[LastValue] BETWEEN 1 AND 999999");
                        });
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("EmailMessages", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.FunctionPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Functions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33a2bbef-fec3-46a8-1e77-b056011221ab"),
                            Code = "accounts.read",
                            Name = "accounts.read"
                        },
                        new
                        {
                            Id = new Guid("225d2c8d-5643-edcc-6264-23023273f4aa"),
                            Code = "accounts.manage-role",
                            Name = "accounts.manage-role"
                        },
                        new
                        {
                            Id = new Guid("1fef387c-5830-f6fc-2b51-d9955724ea9d"),
                            Code = "accounts.manage-status",
                            Name = "accounts.manage-status"
                        },
                        new
                        {
                            Id = new Guid("2d66f26d-2a0f-2f53-5736-21839ccc49aa"),
                            Code = "projects.read",
                            Name = "projects.read"
                        },
                        new
                        {
                            Id = new Guid("fb7562ac-dbd6-04a0-61b5-54989e957389"),
                            Code = "projects.create",
                            Name = "projects.create"
                        },
                        new
                        {
                            Id = new Guid("12463406-673b-7083-4a81-8989f67b6189"),
                            Code = "projects.manage-all",
                            Name = "projects.manage-all"
                        },
                        new
                        {
                            Id = new Guid("7ad8cc35-c156-8e03-1f0f-5dce46d7b02d"),
                            Code = "project-members.manage-all",
                            Name = "project-members.manage-all"
                        },
                        new
                        {
                            Id = new Guid("09ddef94-8813-feef-fe5d-113423733126"),
                            Code = "tasks.read",
                            Name = "tasks.read"
                        },
                        new
                        {
                            Id = new Guid("ae86667d-d332-f2ec-9478-dc11ccfe5538"),
                            Code = "tasks.create",
                            Name = "tasks.create"
                        },
                        new
                        {
                            Id = new Guid("1178b17c-1c93-c9c8-7a84-520956293ab7"),
                            Code = "tasks.update-any",
                            Name = "tasks.update-any"
                        },
                        new
                        {
                            Id = new Guid("9bec3fcd-3ad2-f414-e231-d82c767cd9c8"),
                            Code = "tasks.update-assigned",
                            Name = "tasks.update-assigned"
                        },
                        new
                        {
                            Id = new Guid("642b166d-0bae-4f78-8547-0936c056c947"),
                            Code = "tasks.delete",
                            Name = "tasks.delete"
                        },
                        new
                        {
                            Id = new Guid("3043697f-c4a1-6c56-a8f1-b346752d6c2d"),
                            Code = "comments.read",
                            Name = "comments.read"
                        },
                        new
                        {
                            Id = new Guid("61d4b140-5240-a863-0752-e6a6f15fc5d7"),
                            Code = "comments.create",
                            Name = "comments.create"
                        },
                        new
                        {
                            Id = new Guid("5974465b-fb6d-0942-9e6c-c47a5eeff057"),
                            Code = "comments.update-own",
                            Name = "comments.update-own"
                        },
                        new
                        {
                            Id = new Guid("c2607bb0-d043-de33-2bf9-57e2a4543ca6"),
                            Code = "comments.delete-own",
                            Name = "comments.delete-own"
                        },
                        new
                        {
                            Id = new Guid("f7a62720-6098-cfd6-fb68-68398da844f5"),
                            Code = "preferences.read-own",
                            Name = "preferences.read-own"
                        },
                        new
                        {
                            Id = new Guid("fe9db95a-0800-4e06-4076-737b9a06341d"),
                            Code = "preferences.update-own",
                            Name = "preferences.update-own"
                        });
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("OwnerAccountId", "Status");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("ProjectMembers", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.ProjectMemberRole", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId", "AccountId", "ProjectRoleId");

                    b.HasIndex("ProjectRoleId");

                    b.ToTable("ProjectMemberRoles", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProjectRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcb5403b-db13-d3f9-d0f9-ea2a538dbc52"),
                            Code = "ProjectManager",
                            Name = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("574ad972-8842-17a4-fcb5-6cfc8036198e"),
                            Code = "FrontendDeveloper",
                            Name = "FrontendDeveloper"
                        },
                        new
                        {
                            Id = new Guid("72d1d8f5-5450-875d-977d-f44c03207e3e"),
                            Code = "BackendDeveloper",
                            Name = "BackendDeveloper"
                        },
                        new
                        {
                            Id = new Guid("01110c23-5525-8940-afd8-ad83d7233315"),
                            Code = "SystemAnalyst",
                            Name = "SystemAnalyst"
                        },
                        new
                        {
                            Id = new Guid("8d87e5bf-86ea-3463-29e1-2d0960aabaae"),
                            Code = "Member",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "FamilyId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.RoleFunction", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("RoleFunctions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("33a2bbef-fec3-46a8-1e77-b056011221ab")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("225d2c8d-5643-edcc-6264-23023273f4aa")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("1fef387c-5830-f6fc-2b51-d9955724ea9d")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("2d66f26d-2a0f-2f53-5736-21839ccc49aa")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("fb7562ac-dbd6-04a0-61b5-54989e957389")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("12463406-673b-7083-4a81-8989f67b6189")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("7ad8cc35-c156-8e03-1f0f-5dce46d7b02d")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("09ddef94-8813-feef-fe5d-113423733126")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("ae86667d-d332-f2ec-9478-dc11ccfe5538")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("1178b17c-1c93-c9c8-7a84-520956293ab7")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("9bec3fcd-3ad2-f414-e231-d82c767cd9c8")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("642b166d-0bae-4f78-8547-0936c056c947")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("3043697f-c4a1-6c56-a8f1-b346752d6c2d")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("61d4b140-5240-a863-0752-e6a6f15fc5d7")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("5974465b-fb6d-0942-9e6c-c47a5eeff057")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("c2607bb0-d043-de33-2bf9-57e2a4543ca6")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("f7a62720-6098-cfd6-fb68-68398da844f5")
                        },
                        new
                        {
                            RoleId = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            FunctionId = new Guid("fe9db95a-0800-4e06-4076-737b9a06341d")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("33a2bbef-fec3-46a8-1e77-b056011221ab")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("2d66f26d-2a0f-2f53-5736-21839ccc49aa")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("fb7562ac-dbd6-04a0-61b5-54989e957389")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("12463406-673b-7083-4a81-8989f67b6189")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("7ad8cc35-c156-8e03-1f0f-5dce46d7b02d")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("09ddef94-8813-feef-fe5d-113423733126")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("ae86667d-d332-f2ec-9478-dc11ccfe5538")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("1178b17c-1c93-c9c8-7a84-520956293ab7")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("642b166d-0bae-4f78-8547-0936c056c947")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("3043697f-c4a1-6c56-a8f1-b346752d6c2d")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("61d4b140-5240-a863-0752-e6a6f15fc5d7")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("5974465b-fb6d-0942-9e6c-c47a5eeff057")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("c2607bb0-d043-de33-2bf9-57e2a4543ca6")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("f7a62720-6098-cfd6-fb68-68398da844f5")
                        },
                        new
                        {
                            RoleId = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            FunctionId = new Guid("fe9db95a-0800-4e06-4076-737b9a06341d")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("2d66f26d-2a0f-2f53-5736-21839ccc49aa")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("09ddef94-8813-feef-fe5d-113423733126")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("9bec3fcd-3ad2-f414-e231-d82c767cd9c8")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("3043697f-c4a1-6c56-a8f1-b346752d6c2d")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("61d4b140-5240-a863-0752-e6a6f15fc5d7")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("5974465b-fb6d-0942-9e6c-c47a5eeff057")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("c2607bb0-d043-de33-2bf9-57e2a4543ca6")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("f7a62720-6098-cfd6-fb68-68398da844f5")
                        },
                        new
                        {
                            RoleId = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            FunctionId = new Guid("fe9db95a-0800-4e06-4076-737b9a06341d")
                        },
                        new
                        {
                            RoleId = new Guid("992f6db2-93c5-ffd9-4d68-7bc13e3bf5f5"),
                            FunctionId = new Guid("2d66f26d-2a0f-2f53-5736-21839ccc49aa")
                        },
                        new
                        {
                            RoleId = new Guid("992f6db2-93c5-ffd9-4d68-7bc13e3bf5f5"),
                            FunctionId = new Guid("09ddef94-8813-feef-fe5d-113423733126")
                        },
                        new
                        {
                            RoleId = new Guid("992f6db2-93c5-ffd9-4d68-7bc13e3bf5f5"),
                            FunctionId = new Guid("3043697f-c4a1-6c56-a8f1-b346752d6c2d")
                        },
                        new
                        {
                            RoleId = new Guid("992f6db2-93c5-ffd9-4d68-7bc13e3bf5f5"),
                            FunctionId = new Guid("f7a62720-6098-cfd6-fb68-68398da844f5")
                        });
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAccountId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("ProjectId", "Status", "Deadline");

                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("TaskItemId", "CreatedAt");

                    b.ToTable("TaskItemComments", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("TaskItemId", "CreatedAt");

                    b.ToTable("TaskItemHistories", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SkipBatchConfirmation")
                        .HasColumnType("bit");

                    b.HasKey("AccountId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1adad986-a866-5e9d-7ab2-4273017f01fc"),
                            ConcurrencyStamp = "seed-admin",
                            Description = "最高管理者",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("df98f6d0-8bd9-a99a-f62d-679a362d5b07"),
                            ConcurrencyStamp = "seed-administrator",
                            Description = "後台管理員",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("0a787aeb-cdd8-4f4d-bad5-443dde035c41"),
                            ConcurrencyStamp = "seed-user",
                            Description = "一般使用者",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("992f6db2-93c5-ffd9-4d68-7bc13e3bf5f5"),
                            ConcurrencyStamp = "seed-viewer",
                            Description = "瀏覽者",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("ProjectManagementWeb.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccountRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.ProjectMemberRole", b =>
                {
                    b.HasOne("ProjectManagementWeb.Domain.Entities.ProjectRole", null)
                        .WithMany()
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Domain.Entities.ProjectMember", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.RoleFunction", b =>
                {
                    b.HasOne("ProjectManagementWeb.Domain.Entities.FunctionPermission", null)
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItemComment", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.TaskItemHistory", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("ProjectManagementWeb.Domain.Entities.UserPreference", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagementWeb.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
